tap "caskroom/drivers"
tap "caskroom/fonts"
cask "font-source-code-pro"

cask "1password"
cask "aerial"
cask "alfred"
cask "arq"
cask "atom"
cask "bartender"
cask "daisydisk"
cask "deluge"
cask "docker"
cask "dropbox"
cask "font-source-code-pro"
cask "google-chrome"
cask "hazel"
cask "iterm2"
cask "keepingyouawake"
cask "keybase"
cask "ksdiff"
cask "licecap"
cask "little-snitch"
cask "mplayerx"
cask "openemu"
cask "plex-media-server"
cask "printopia"
cask "sabnzbd"
# License not updated for latest sketch
# cask "sketch"
cask "slack"
cask "sonarr"
cask "steam"
cask "the-unarchiver"
cask "unifi-controller"
cask "xbox360-controller-driver"

brew "bash-completion"
brew "ccat"
brew "git"
brew "go"
brew "headphones"
brew "httpie"
brew "hub"
brew "jq"
brew "mackup"
brew "mas"
brew "mr"
brew "youtube-dl"

if ENV["API_KEY"]
  cask "prey"
else
  print "Set `API_KEY` environment variable to install prey..."
end
